Vagrant.configure('2') do |config|
	# Multiple calls to 'vm' function with different names as the
	# second argument each time. Only the last name should have the
	# block that configures ansible, otherwise, Ansible will be run
	# multiple times
	vm(config, 'vm', 'rhel7.4') do |vm|
		ansible(vm) do |ansible|
			ansible.groups = {
				'some_host_group' => ['vm']
			}
		end
	end
end
